export const INITIAL_STATE = {
  user: {},
  userIsLoading: true,
  userErrorMessage: null,
  syncIsLoading: false,
  syncErrorMessage: null,
  contactInfo: null,
  contactInfoLoading: null,
  contactInfoErrorMessage: null,
  helpRequests: [],
  helpRequestsLoading: [],
  helpRequestsErrorMessage: null,
  addContactErrorMessage: null,
  removeContactErrorMessage: null,
}
